In [3]:
import numpy as np

In [4]:
# create an array using numpy arrays

a = np.array([[1,2,3],[4,5,6]])

print(a)

[[1 2 3]
 [4 5 6]]


In [5]:
# arange function is use for print number form a to b and skip c at same interval
# function call => numpy.arange(from,to,step)

print(np.arange(0,10))

print(np.arange(0,10,2))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [6]:
# linespace is used to create an evenly spaced sequence in a specified interval.
# there are 3 arguments in function call from to and total space in array

a = np.linspace(0,10,4)

print(a)

[ 0.          3.33333333  6.66666667 10.        ]


In [7]:
# np.zeroes give matrinx or array given size in argumrtn
# np.ones is also works like np.zeroes

x = np.zeros((5,3))

print(x)

y= np.ones(3)

print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]


In [8]:
# np.eye crete an identity matrix of size given in function argumetn

a = np.eye(4)

print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
# Create an array of the given shape and populate it with random samples from a uniform distribution over 0 to 1

z = np.random.rand(3,4)

print(z)

# Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform

x = np.random.randn(4)

print(x)

# return n random integers from low to high given in argument if not given n in argument then return only one random integer


np.random.randint(2,20,3)

[[0.34727615 0.27649257 0.58028773 0.10261339]
 [0.58006243 0.82589364 0.89422142 0.91121244]
 [0.47388589 0.00454732 0.05826141 0.61012832]]
[ 0.70610658 -0.59455944  0.89737169 -1.13559536]


array([13, 12,  3])

In [10]:
# Returns an array containing the same data with a new shape.

a = np.array([[1, 2, 3], [4, 5,6]])

print('before reshape ...')
print(a.shape)
print(a)


print('\nafter reshape ...')
a = a.reshape((3,2))
print(a.shape)
print(a)

before reshape ...
(2, 3)
[[1 2 3]
 [4 5 6]]

after reshape ...
(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [11]:
print(a.max()) #return max value of array a

print(a.min()) #return min value of array a

print(a.argmax()) #return max value element's index of array a

print(a.argmin()) #return min element's index of array a

print(a.dtype) #dtype return data type of the object of an array

6
1
5
0
int32


In [19]:
ar = np.arange(0,11)

print(ar)

x = ar[1:5]

print(x)

# Numpy arrays differ from a normal Python list because of their ability to broadcast

ar[1:5] = 50

print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10]
[1 2 3 4]
[ 0 50 50 50 50  5  6  7  8  9 10]


In [ ]:
# Indexing in 2D arrays

array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

