In [2]:
import numpy as np

In [3]:
# create an array using numpy arrays

a = np.array([[1,2,3],[4,5,6]])

print(a)

[[1 2 3]
 [4 5 6]]


In [4]:
# arange function is use for print number form a to b and skip c at same interval
# function call => numpy.arange(from,to,step)

print(np.arange(0,10))

print(np.arange(0,10,2))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [5]:
# linespace is used to create an evenly spaced sequence in a specified interval.
# there are 3 arguments in function call from to and total space in array

a = np.linspace(0,10,4)

print(a)

[ 0.          3.33333333  6.66666667 10.        ]


In [6]:
# np.zeroes give matrinx or array given size in argumrtn
# np.ones is also works like np.zeroes

x = np.zeros((5,3))

print(x)

y= np.ones(3)

print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]


In [8]:
# np.eye crete an identity matrix of size given in function argumetn

a = np.eye(4)

print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
# Create an array of the given shape and populate it with random samples from a uniform distribution over 0 to 1

z = np.random.rand(3,4)

print(z)

# Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform

x = np.random.randn(4)

print(x)

# return n random integers from low to high given in argument if not given n in argument then return only one random integer


np.random.randint(2,20,3)

[[0.69421482 0.44589647 0.90610819 0.91232768]
 [0.93854372 0.8518594  0.32378438 0.41146979]
 [0.49060504 0.68642186 0.52922128 0.33531124]]
[-1.08447275 -0.47764875 -0.16328785 -0.40188614]


array([12,  4, 16])

In [13]:
# Returns an array containing the same data with a new shape.

a = np.array([[1, 2, 3], [4, 5,6]])

print('before reshape ...')
print(a.shape)
print(a)


print('\nafter reshape ...')
a = a.reshape((3,2))
print(a.shape)
print(a)

before reshape ...
(2, 3)
[[1 2 3]
 [4 5 6]]

after reshape ...
(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [14]:
print(a.max()) #return max value of array a

print(a.min()) #return min value of array a

print(a.argmax()) #return max value element's index of array a

print(a.argmin()) #return min element's index of array a

print(a.dtype) #dtype return data type of the object of an array

6
1
5
0
int32


In [15]:
ar = np.arange(0,11)

print(ar)

x = ar[1:5]

print(x)

# Numpy arrays differ from a normal Python list because of their ability to broadcast

ar[1:5] = 50

print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10]
[1 2 3 4]
[ 0 50 50 50 50  5  6  7  8  9 10]


In [22]:
# Indexing in 2D arrays

array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(array_2d)

# indexing or print whole row

print(array_2d[1])

# get particullar elements

print(array_2d[1][2])

# another method
print(array_2d[1 , 2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
6
6


In [23]:
# 2D array slicing

#Shape (2,2) from top right corner

print(array_2d[:2,1:])

# another way to print whole row

print(array_2d[2,:])

[[2 3]
 [5 6]]
[7 8 9]


In [31]:
# create one new 2d array of size 10x10

arr2d = np.zeros((10,9))

print(arr2d)

# find row length of array

arr_row = arr2d.shape[0]

print(arr_row)

# find column length  of array

arr_column = arr2d.shape[1]

print(arr_column)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
10
9


In [37]:
for i in range(arr_row) :
    arr2d[i] = i

print(arr2d)

# print only mentioned row

print("\n" , arr2d[[2,4,6,8]])

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9.]]

 [[2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8.]]


In [44]:
# selection

arr = np.arange(0,11)

print(arr)

# print boolean value array as per the operation

print(arr>5)

# now from boolean value print the array which value is true

bool_array = arr>4

print(arr[bool_array])

x=2

print(arr[arr>x])

[ 0  1  2  3  4  5  6  7  8  9 10]
[False False False False False False  True  True  True  True  True]
[ 5  6  7  8  9 10]
[ 3  4  5  6  7  8  9 10]


In [55]:
# numpy arethmentic operations

# addition
arr1 = np.arange(20,31)
arr = arr + arr1

print(arr)

print("\n")
print(np.add(arr, arr1))

# subtraction

arr = arr1 - arr

print("\n",arr)

print("\n")
print(np.subtract(arr, arr1))

# multiplication

print(arr*arr1)

print("\n",np.multiply(arr, arr1))

# division

arr1 = np.arange(21,31)
arr = np.arange(1,11)

print(arr1 / arr)

print("\n",np.divide(arr1, arr))



[20 22 24 26 28 30 32 34 36 38 40]


[40 43 46 49 52 55 58 61 64 67 70]

 [  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10]


[-20 -22 -24 -26 -28 -30 -32 -34 -36 -38 -40]
[   0  -21  -44  -69  -96 -125 -156 -189 -224 -261 -300]

 [   0  -21  -44  -69  -96 -125 -156 -189 -224 -261 -300]
[21.         11.          7.66666667  6.          5.          4.33333333
  3.85714286  3.5         3.22222222  3.        ]

 [21.         11.          7.66666667  6.          5.          4.33333333
  3.85714286  3.5         3.22222222  3.        ]


In [9]:
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])

# vstack done vertical stacking

np.vstack((n1,n2))

# hctack done horizontal stacking

np.hstack((n1,n2))

# column stack

np.column_stack((n1,n2))

# row stack is similar like verical stacking

np.row_stack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
n1 = np.array([1, 2, 3, 4, 5, 6])
n2 = np.array([5, 6, 7, 8])

# intersect1d find common element in both array

np.intersect1d(n1, n2)

# setdiff1d find unique elements in first array from second array

np.setdiff1d(n1, n2)

array([1, 2, 3, 4])

In [20]:
arr = np.array([1,5,8,10,25,13,45,27])

# to find mean of given array elements

print(np.mean(arr))

# to find meadian of given array elements

print(np.median(arr))

# find standard deviation of given array elements

print(np.std(arr))

16.75
11.5
13.663363421939708


In [23]:
# matrix multiplication

n1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

n2 = np.array([[9,8,7],[6,5,4],[3,2,1]])

n1.dot(n2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [27]:
# NumoPy Save and load

n1 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

np.save('numpy_array',n1)

n2 = np.load('numpy_array.npy')

n2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])